name: 'Generate Env File'
description: 'Generate Env File'
inputs:
  variables:
    required: true
runs:
  using: "composite"
  steps: 
     - 
      name: Generate Env File
      id: generate_file
      shell: bash
      run: |
        t=${{ inputs.variables }}
        a=($(echo "$t" | tr ',' '\n'))
        for i in "${array[@]}"
        do
          echo "x=$i"
        done
