name: 'Generate Env File'
description: 'Generate Env File'
inputs:
  variables:
    required: true
runs:
  using: "composite"
  steps: 
     - 
      name: Generate Env File
      id: generate_file
      shell: bash
      run: |
        t=${{ inputs.variables }}
        echo $t
        sentence=${sentence//,/$'\n'}  # change the semicolons to white space
        for word in $sentence
        do
            echo "word=$word"
        done
