server:
  port: 3000
mqtt:
  adress: tcp://localhost
  user: mqtt
  password: mqtt
log4js:
  appenders:
    stdout:
      type: stdout
    err:
      type: stderr
  categories:
    default:
      appenders:
        - stdout
      level: info
    stdout:
      appenders:
        - stdout
      level: info
    debug:
      appenders:
        - stdout
      level: debug
    http:
      appenders:
        - stdout
      level: error
    mqtt:
      appenders:
        - stdout
      level: error
    auto:
      appenders:
        - stdout
      level: info
    security:
      appenders:
        - err
      level: error
