server:
  port: 3000
mqtt:
  adress: tcp://atlantis.fritz.box
  user: http2mqtt
  password: http2mqttPass
log4js:
  appenders:
    stdout:
      type: stdout
    err:
      type: stderr
  categories:
    default:
      appenders:
        - stdout
      level: debug
    stdout:
      appenders:
        - stdout
      level: debug
    debug:
      appenders:
        - stdout
      level: debug
    http:
      appenders:
        - stdout
      level: debug
    mqtt:
      appenders:
        - stdout
      level: debug
    auto:
      appenders:
        - stdout
      level: debug
    security:
      appenders:
        - err
      level: info
