server:
  port: 3000
log4js:
  appenders:
    stdout:
      type: stdout
    err:
      type: stderr
  categories:
    default:
      appenders:
        - stdout
      level: info
    stdout:
      appenders:
        - stdout
      level: info
    debug:
      appenders:
        - stdout
      level: debug
    http:
      appenders:
        - stdout
      level: info
    auto:
      appenders:
        - stdout
      level: info
    security:
      appenders:
        - err
      level: error
