name: 'Load Env File'
description: 'Load Env File'
runs:
  using: "composite"
  steps: 
     - 
      name: Generate Env File
      id: generate_file
      shell: bash
      run: |
        while read -r line; do
            t_envs=$(echo $line | tr "=" "\n")
            t_name=t_envs[0]
            t_value=t_envs[1]
            echo "$t_name => $t_value"
        done < /tmp/env
