name: 'Generate Versions'
description: 'Extract Versions from changelog'
inputs:
  VERSION:
    required: true
  VERSION_RELEASE:
    required: true
  VERSION_MINOR:
    required: true
  branch:
    required: true
    default: true
  isNightly:
    required: true
    default: false
outputs:
  TAGS: 
    description: "TAGS"
    value: ${{ steps.generate_tags.outputs.TAGS }}
runs:
  using: "composite"
  steps: 
     - 
      name: Generate Tags
      id: generate_tags
      shell: bash
      run: |
        TAGS=""
        IMAGENAME="$IMAGE_NAME"
        if [ ${{ inputs.branch }} = 'master' ] ; then
            if [ ${{ inputs.isNightly }} = true ] ; then
             echo 'Generate Nightly Tags'
             TAGS=`echo -e "$IMAGENAME:latest-nightly\n$IMAGENAME:$VERSION-nightly\n$IMAGENAME:$VERSION_MINOR-nightly"`
            else 
              echo 'Generate Master Tags'
              TAGS=`echo -e "$IMAGENAME:latest\n$IMAGENAME:$VERSION\n$IMAGENAME:$VERSION_MINOR"`
            fi
        elif [ ${{ inputs.branch }} = 'dev' ] ; then
           TAGS=`echo -e "$IMAGENAME:latest-dev\n$IMAGENAME:$VERSION-dev\n$IMAGENAME:$VERSION_MINOR-dev"`
        fi
        echo "$TAGS"
        echo "::set-output name=TAGS::$TAGS"
        echo "::set-env name=TAGS::$TAGS"
