name: docker

env:
  IMAGE_NAME: jschnabel/heimdall

on:
  push:
    branches: master
jobs:
  prepair:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: genVersions
        name: Generate Versions
        uses: ./.github/actions/genVersions
      - 
        id: genTags
        name: Generate Tags
        uses: ./.github/actions/genTags
        with:
          VERSION: $VERSION
          VERSION_RELEASE: $VERSION_RELEASE
          VERSION_MINOR: $VERSION_MINOR
          branch: ${{ github.ref }}
          isNightly: ${{ github.event_name == 'schedule' }}
      - 
        name: Generate Env File
        uses: ./.github/actions/generateEnv
        with:
          variables: |
            VERSION
            VERSION_RELEASE
            VERSION_MINOR
            TAGS
  docker:
    needs: [prepair]
    runs-on: ubuntu-latest
    steps:
     - 
      name: Checkout
      uses: actions/checkout@v2
     -
      name: Build Images
      run: |
       echo "VERSION=${{ env.VERSION }}"
       echo "GITHASH=${{ env.GITHASH }}"
       echo "DOCKERTAGS=${{ env.DOCKERTAGS }}"
       echo "ABC=${{ env.ABC }}"
