name: docker

env:
  IMAGE_NAME: jschnabel/heimdall

on:
  push:
    branches: master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
     - 
      name: Checkout
      uses: actions/checkout@v2
     - 
      id: genVersions
      name: Generate Versions
      uses: ./.github/actions/genVersions
     -
      name: Build Images
      run: |
       cat ${{ github.event_path }}
