name: docker

on:
  push:
    branches: master

jobs:
  predocker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: BUILD_DATE
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ date -u +"%Y-%m-%dT%H:%M:%SZ" }}
        variable: BUILD_DATE
    - 
      name: VCS_REF
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ $(git rev-parse --short "$GITHUB_SHA") }}
        variable: VCS_REF
    - 
      name: VERSION
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ head -n 1 ./CHANGELOG }}
        variable: VERSION
  docker:
    runs-on: ubuntu-latest
    needs: predocker
    if: github.ref == 'refs/heads/master'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        uses: nick-invision/persist-action-data@v1
        with:
          retrieve_variables: BUILD_DATE,VERSION,VCS_REF
      - 
        run: |
          echo $BUILD_DATE
          echo $VERSION
          echo $VCS_REF
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v6,linux/arm64
          push: true
          tags: | 
            jschnabel/heimdall.js:latest
            jschnabel/heimdall.js:dev
          build-args: |
            BUILD_DATE=$BUILD_DATE
            VCS_REF=
            VERSION=
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
