name: docker

env:
  IMAGE_NAME: jschnabel/heimdall

on:
  push:
    branches: master
jobs:
  predocker:
    runs-on: ubuntu-latest
    steps:
     - 
        name: Checkout
        uses: actions/checkout@v2
     - 
      name: Generate ENV
      id: generate_env
      run: |
        VERSION=$(head -n 1 ./CHANGELOG | awk '{print tolower($0)}')
        VERSION_RELEASE=$(echo $VERSION | cut -d '-' -f 2 -s)
        VERSION_PATCH=${VERSION%-*}
        VERSION_MINOR=${VERSION_PATCH%.*}
        BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        GITHASH=$(git rev-parse "$GITHUB_SHA")
        echo "VERSION=$VERSION"
        echo "BUILD_DATE=$BUILD_DATE"
        echo "GITHASH=$GITHUB_SHA"
        echo "VERSION_RELEASE=$VERSION_RELEASE"
        echo "VERSION_PATCH=$VERSION_PATCH"
        echo "VERSION_MINOR=$VERSION_MINOR"
        
        echo "::set-output name=VERSION::$VERSION"
        echo "::set-output name=BUILD_DATE::$BUILD_DATE"
        echo "::set-output name=GITHASH::$GITHASH"
        
        echo "::set-env name=VERSION::$VERSION"
        echo "::set-env name=VERSION_RELEASE::$VERSION_RELEASE"
        echo "::set-env name=VERSION_PATCH::$VERSION_PATCH"
        echo "::set-env name=VERSION_MINOR::$VERSION_MINOR"
        
        echo "${{ github.event.push.type }}"
     - 
      name: Generate Master Tags
      id: generate_tags_master
      if: github.ref == 'refs/heads/master'
      run: |
        TAGS="$IMAGE_NAME:$VERSION\n$IMAGE_NAME:$VERSION_MINOR\n$IMAGE_NAME:latest"
        echo "::set-output name=TAGS::$TAGS"
     - 
      name: Generate Dev Tags
      id: generate_tags_dev
      if: github.ref == 'refs/heads/dev'
      run: |
        TAGS="$IMAGE_NAME:$VERSION\n$IMAGE_NAME:$VERSION_MINOR-$VERSION_RELEASE\n$IMAGE_NAME:dev-latest"
        echo "::set-output name=TAGS::$TAGS"
     - 
      name: GITHASH
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ steps.generate_env.outputs.GITHASH }}
        variable: GITHASH
     - 
      name: BUILD_DATE
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ steps.generate_env.outputs.BUILD_DATE }}
        variable: BUILD_DATE
     - 
      name: VERSION
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ steps.generate_env.outputs.VERSION }}
        variable: VERSION
     - 
      name: TAGS
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ steps.generate_env.outputs.TAGS }}
        variable: TAGS

  docker:
    runs-on: ubuntu-latest
    needs: predocker
    if: github.ref == 'refs/heads/master2'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Images
        uses: ./.github/actions/buildImages
